### ISSUE TITLE
License.properties Typo

### ISSUE THREAD

**Issue by micheee** [oxygenxml/webapp-storage-services-integration#1]
I guess there might be a typo in the [readme](/oxygenxml/webapp-storage-services-integration/blob/master/ss-oxygen-sample-webapp/README.md):

> Another important file that needs to be placed in the src/main/webapp/WEB-INF/ folder is the  license.txt

I guess license.properties is the right filename?

**Comment by ctalau** [comment]
Thanks for noticing. I updated the description.

**Comment by micheee** [comment]
You're welcome! I wasn't so sure if I were right, otherweise I would have proposed a pull request directly :+1:
